version: 2
machine:
  node:
    version: 8.9.4

test:
  override:
    - echo 'skipping test'

jobs:
  build:
    working_directory: ~/angular-web-bluetooth
    docker:
      - image: circleci/node:8.9.4-browsers
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ~/.cache/npm
            - ./node_modules
      - run:
          name: angular-build
          command: npm run build
      - store_artifacts:
          path: ~/angular-web-bluetooth/dist